services:
  front:
    image: ${FRONT_IMAGE_NAME}
    env_file: apps/front/.env
    networks:
        - libera-net
    build:
      context: .
      dockerfile: apps/front/docker/prod.Dockerfile
    restart: always
    ports:
      - '${FRONT_PORT}:3000'
volumes:
  mysql_data:
networks:
  libera-net: