services:
  backend:
    image: ${BACKEND_IMAGE_NAME}
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - '${BACKEND_PORT}:3002'
    networks:
      - libera-net

  front:
    image: ${FRONT_IMAGE_NAME}
    env_file: apps/front/.env
    networks:
        - libera-net
    build:
      context: .
      dockerfile: apps/front/docker/prod.Dockerfile
    restart: always
    ports:
      - '${FRONT_PORT}:3000'
networks:
  libera-net: