services:
  database:
    image: mysql:8
    container_name: library-mysql
    restart: always
    env_file:
      - .env
    ports:
    - "0.0.0.0:${DATABASE_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  front:
    image: ${FRONT_IMAGE_NAME}
    env_file: apps/front/.env
    build:
      context: .
      dockerfile: apps/front/docker/prod.Dockerfile
    restart: always
    ports:
      - "0.0.0.0:${FRONT_PORT}:3000"
  backend:
    depends_on:
      - database
    image: ${BACKEND_IMAGE_NAME}
    env_file: apps/backend/.env
    build:
      context: .
      dockerfile: ./apps/backend/docker/prod.Dockerfile
    restart: always
    ports:
      - "0.0.0.0:${BACKEND_PORT}:3000"
volumes:
  mysql_data: